# Docs for the Azure Functions Deploy action: https://github.com/Azure/functions-action
name: Build and deploy dotnet core app to Azure Function App - func-fortianswer

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_PATH: src/orchestrator/FortiAnswer.Orchestrator/FortiAnswer_Orchestrator.csproj
  DOTNET_VERSION: '8.0.x'
  PUBLISH_DIR: published

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        shell: pwsh
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        shell: pwsh
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        shell: pwsh
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }} --no-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2CACB550134D46B48799B62590600659 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94C1C90ADD2943F5ACF89CB9CD1F542B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1ED18C41E9274A4681299A059FF350F8 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-fortianswer
          slot-name: Production
          package: ${{ env.PUBLISH_DIR }}
